name: Test Python Versions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
        python-version: [3.6]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      env:
        AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache     
      with:
        python-version: ${{ matrix.python-version }}
    - run: python --version
