name: Test Python Versions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.6.11]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      env:
        AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache     
      with:
        python-version: ${{ matrix.python-version }}
    - run: python --version
