name: Simple Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  simple:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Show system info
      run: |
        hostname
        uname -a
        whoami
        date
        ls -asl
        
